---
{{- if .Values.multus.n4Interface.create }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-n4
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": {{- cat .Values.multus.n4Interface.hostInterface | nospace | quote }},
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.n4Interface.Ipadd "/" .Values.multus.n4Interface.Netmask | nospace | quote }}
                }
        ]
        {{- if .Values.multus.n4Interface.routes }}
        ,"routes":  {{- .Values.multus.n4Interface.routes | toJson }}
        {{- end }}
      }
    }'
{{- end }}
---