############# Common configuration

# Log level
log_level:
  general: debug

http_version: 2  # allowed value 1 and 2, make sure all NFs use the same HTTP version

############## SBI Interfaces
### Each NF takes its local SBI interfaces and remote interfaces from here, unless it gets them using NRF discovery mechanisms
nfs:
  nrf:
    host: oai-nrf
    sbi:
      port: 80
      api_version: v1
      interface_name: eth0

############## NF-specific configuration
nrf:
  nrf_name: "OAI-NRF"